spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: abhishek.magdum.07@gmail.com
    password: tdqlptvopqtlsohn
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true